package user.exception;

class User{
	public void go() {
		int i=10; int j = 0; int z =0;
		//저 아래 부분에서 j가 분모인 연산이 진행된다는 가정아래...
		
		System.out.println("폭탄 터트리기 직전...");
		//j가 0이면 예외를 터뜨리겠다는 말(예외 객체를 내가 직접 생성)
		if(j==0) throw new ArithmeticException();
		System.out.println("폭탄 터진 직후	...");
		z= i /j;
	}
}

public class UserExceptionTest1 {

	public static void main(String[] args) {
		User u = new User();
		System.out.println("go () calling...");
		u.go();
		
	}

}
